





SELECT TOP(18) * INTO dbo.TBLINSATEST FROM dbo.TBLINSA 

SELECT * FROM dbo.TBLINSATEST WITH(NOLOCK)

ALTER TABLE dbo.TBLINSATEST ALTER COLUMN name CHAR(850) NOT NULL

CREATE INDEX IDX__TBLINSATEST__NAME ON dbo.TBLINSATEST (name) WITH (FILLFACTOR=100,PAD_INDEX=ON)

SELECT * FROM dbo.TBLINSATEST WITH(NOLOCK)

alter table dbo.TBLINSATEST add constraint PK__TBLINSATEST__NUM primary key (num)


SELECT * FROM sys.indexes WITH(NOLOCK) WHERE object_id = object_id('TBLINSATEST')

DBCC IND('ADMIN','TBLINSATEST',2)

SELECT * FROM sys.indexes WITH(NOLOCK) WHERE object_id = object_id('TBLINSATEST')
SELECT * FROM dbo.TBLINSATEST WITH(NOLOCK)


DBCC IND('ADMIN','TBLINSATEST',2)

--ROOT PAGE
DBCC PAGE('ADMIN',1,122064,3)

--LEAF PAGE
DBCC PAGE('ADMIN',1,122024,3)
DBCC PAGE('ADMIN',1,122032,3)
DBCC PAGE('ADMIN',1,122033,3)



DBCC PAGE('ADMIN',1,138393,3)


BEGIN TRAN

ROLLBACK TRAN


INSERT INTO dbo.TBLINSATEST VALUES (1030,'이기고','760521-1089937','2019-11-11',N'서울','010-6658-7844',N'기획부',N'사원',960000,146000)

DBCC IND('ADMIN','TBLINSATEST',2)


SELECT index_id,name FROM sys.indexes WITH(NOLOCK) WHERE object_id = object_id('TBLINSA')

DBCC IND('ADMIN','TBLINSA',10)

DBCC IND('ADMIN','KAKAO_PRODUCT_TABLE',1)

--SELECT * FROM dbo.TBLINSA WITH(NOLOCK) WHERE name = N'유관순'


create index IDX__TBLINSA__NAME on dbo.TBLINSA (name) with (fillfactor=1,pad_index=on)

DBCC IND('ADMIN','TBLINSA',10)

drop index IDX__TBLINSA__NAME on dbo.tblinsa

select * from dbo.tblinsa with(nolock)


SELECT TOP(9) * INTO dbo.TBLINSATEST FROM dbo.TBLINSA 


SELECT TOP(20) * INTO dbo.TBLINSATEST FROM dbo.TBLINSA

SELECT * FROM dbo.TBLINSATEST WITH(NOLOCK)

DROP TABLE dbo.TBLINSATEST


SELECT * FROM dbo.TBLINSA WITH(NOLOCK)

CREATE INDEX IDX__TBLINSA__NAME

CREATE INDEX IDX__TBLINSA__NAME ON dbo.TBLINSA (name) WITH (FILLFACTOR=100,PAD_INDEX=ON)




ALTER TABLE dbo.TBLINSA ALTER COLUMN name CHAR(850) NOT NULL



DROP INDEX IDX__TBLINSA__NAME on dbo.TBLINSATEST

CREATE INDEX IDX__TBLINSATEST__NAME__BASICPAY ON dbo.TBLINSATEST (basicPay,sudang) WITH (FILLFACTOR=1,PAD_INDEX=ON)
SELECT index_id,NAME FROM dbo.TBLINSATEST WITH(NOLOCK)

CREATE INDEX IDX__TBLINSA__NAME ON dbo.TBLINSATEST (name) WITH (FILLFACTOR=1,PAD_INDEX=ON)


SELECT index_id,name FROM sys.indexes WITH(NOLOCK) WHERE object_id = object_id('TBLINSATEST')


SELECT * FROM sys.indexes WITH(NOLOCK) WHERE object_id = object_id('TBLINSATEST')

SELECT * FROM dbo.TBLINSATEST WITH(NOLOCK)

drop index  IDX__TBLINSATEST__BASICPAY__SUDANG ON dbo.TBLINSATEST

CREATE INDEX IDX__TBLINSATEST__BASICPAY__SUDANG ON dbo.TBLINSATEST (basicPay,sudang) WITH (FILLFACTOR=1,PAD_INDEX=ON)


SELECT * FROM dbo.TBLINSATEST WITH(NOLOCK)


SELECT * FROM sys.indexes WITH(NOLOCK) WHERE object_id = object_id('TBLINSA')


DBCC IND('ADMIN','TBLINSA',5)

170744
170752
170753
170754
170755

SELECT * FROM dbo.TBLINSATEST WITH(NOLOCK)

--950000	145000

BEGIN TRAN

ROLLBACK TRAN

SELECT @@TRANCOUNT


INSERT INTO dbo.TBLINSATEST VALUES (1010,N'김구라','760521-1089937','2019-11-11',N'서울','010-6658-7844',N'기획부',N'대리',960000,146000)
INSERT INTO dbo.TBLINSATEST VALUES (1011,N'김구라2','760521-1089937','2019-11-11',N'서울','010-6658-7844',N'기획부',N'대리',965000,147000)


DBCC TRACEON(3604)
221616
221624
221625

--LEVEL 1
DBCC PAGE('ADMIN',1,122072,3)

--LEVEL 0
DBCC PAGE('ADMIN',1,256640,3)
DBCC PAGE('ADMIN',1,256648,3)
DBCC PAGE('ADMIN',1,256649,3)


DBCC IND('ADMIN','TBLINSATEST',2)


--LEVEL 1
DBCC PAGE('ADMIN',1,170784,3)
DBCC PAGE('ADMIN',1,170760,3)

--LEVEL 0
DBCC PAGE('ADMIN',1,170744,3)
DBCC PAGE('ADMIN',1,170752,3)
DBCC PAGE('ADMIN',1,170753,3)
DBCC PAGE('ADMIN',1,170754,3)
DBCC PAGE('ADMIN',1,170755,3)

SELECT * FROM DB_ID ( [ADMIN] )   


SELECT * FROM sys.indexes WITH(NOLOCK) WHERE object_id = object_id('TBLINSATEST')

SELECT * FROM dbo.TBLINSATEST WITH(NOLOCK)

DROP TABLE dbo.TBLINSATEST

SELECT * FROM sys.dm_db_page_info (1, 1, 170744, DEFAULT ) 


SELECT * FROM dbo.TBLINSATEST WITH(NOLOCK) WHERE name = N'정한국'


drop table dbo.TBLINSATEST


select * from dbo.QOO10_USER_REAL_SH with(nolock)


select top(10000) * into dbo.QOO10_USER_REAL_SH from dbo.QOO10_USER_REAL



select * from dbo.QOO10_USER_REAL_SH with(nolock)

alter table dbo.QOO10_USER_REAL_SH add constraint PK__QOO10_USER_REAL_SH__QOOUSER_SEQ primary key (qoouser_seq)

SELECT * FROM sys.indexes WITH(NOLOCK) WHERE object_id = object_id('QOO10_USER_REAL_SH')


DBCC IND('ADMIN','QOO10_USER_REAL_SH',2)

DBCC PAGE('ADMIN',1,152308,3)

create index idx__test on dbo.QOO10_USER_REAL_SH (qoouser_hascoin,qoouser_register_datetime)






select * from dbo.QOO10_USER_REAL_SH with(nolock)
where qoouser_hascoin = 100000







