

SELECT index_id,name FROM sys.indexes WITH(NOLOCK) WHERE object_id = object_id('TBLINSA')

DBCC IND('ADMIN','TBLINSA',10)

DBCC IND('ADMIN','KAKAO_PRODUCT_TABLE',1)

--SELECT * FROM dbo.TBLINSA WITH(NOLOCK) WHERE name = N'유관순'


create index IDX__TBLINSA__NAME on dbo.TBLINSA (name) with (fillfactor=1,pad_index=on)

DBCC IND('ADMIN','TBLINSA',10)

drop index IDX__TBLINSA__NAME on dbo.tblinsa

select * from dbo.tblinsa with(nolock)


SELECT TOP(9) * INTO dbo.TBLINSATEST FROM dbo.TBLINSA 


SELECT TOP(20) * INTO dbo.TBLINSATEST FROM dbo.TBLINSA

SELECT * FROM dbo.TBLINSATEST WITH(NOLOCK)

DROP TABLE dbo.TBLINSATEST


DROP INDEX IDX__TBLINSA__NAME on dbo.TBLINSATEST

CREATE INDEX IDX__TBLINSATEST__NAME__BASICPAY ON dbo.TBLINSATEST (basicPay,sudang) WITH (FILLFACTOR=1,PAD_INDEX=ON)
SELECT index_id,NAME FROM dbo.TBLINSATEST WITH(NOLOCK)

CREATE INDEX IDX__TBLINSA__NAME ON dbo.TBLINSATEST (name) WITH (FILLFACTOR=1,PAD_INDEX=ON)


SELECT index_id,name FROM sys.indexes WITH(NOLOCK) WHERE object_id = object_id('TBLINSATEST')


SELECT * FROM sys.indexes WITH(NOLOCK) WHERE object_id = object_id('TBLINSATEST')

SELECT * FROM dbo.TBLINSATEST WITH(NOLOCK)

drop index  IDX__TBLINSATEST__NAME__BASICPAY ON dbo.TBLINSATEST

CREATE INDEX IDX__TBLINSATEST__BASICPAY__SUDANG ON dbo.TBLINSATEST (basicPay,sudang) WITH (FILLFACTOR=1,PAD_INDEX=ON)


SELECT * FROM dbo.TBLINSATEST WITH(NOLOCK)

DBCC IND('ADMIN','TBLINSATEST',2)

170744
170752
170753
170754
170755

SELECT * FROM dbo.TBLINSATEST WITH(NOLOCK)


DBCC TRACEON(3604)
221616
221624
221625

--LEVEL 1
DBCC PAGE('ADMIN',1,256680,3)

--LEVEL 0
DBCC PAGE('ADMIN',1,256640,3)
DBCC PAGE('ADMIN',1,256648,3)
DBCC PAGE('ADMIN',1,256649,3)





--LEVEL 1
DBCC PAGE('ADMIN',1,170784,3)
DBCC PAGE('ADMIN',1,170760,3)

--LEVEL 0
DBCC PAGE('ADMIN',1,170744,3)
DBCC PAGE('ADMIN',1,170752,3)
DBCC PAGE('ADMIN',1,170753,3)
DBCC PAGE('ADMIN',1,170754,3)
DBCC PAGE('ADMIN',1,170755,3)

SELECT * FROM DB_ID ( [ADMIN] )   


SELECT * FROM sys.indexes WITH(NOLOCK) WHERE object_id = object_id('TBLINSATEST')

SELECT * FROM dbo.TBLINSATEST WITH(NOLOCK)


SELECT * FROM sys.dm_db_page_info (1, 1, 170744, DEFAULT ) 


SELECT * FROM dbo.TBLINSATEST WITH(NOLOCK) WHERE name = N'정한국'